name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.200'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the project (Generate EXE)
        run: dotnet publish -c Release -r win-x64 --self-contained false --output ./publish

      - name: Archive the build output
        uses: actions/upload-artifact@v4
        with:
          name: LoadTestExe
          path: ./publish/LoadTest.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/LoadTest.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
